### ISSUE TITLE
significance of while(1)

### ISSUE THREAD

**Issue by julianheavyside** [julianheavyside/diversification#10]
@mwpennell see https://github.com/julianheavyside/diversification/blob/master/supporting-functions.R#L56

Does this force the condition to be true forever? break() terminates it when i many datasets have been collected?

**Comment by mwpennell** [comment]
precisely. while this construction is useful, it is also dangerous as it may run forever...

**Comment by mwpennell** [comment]
Just a note on this (that is definitely non-obvious)

`while(1)` is equivalent to saying `while(TRUE)` since in binary land 1 is TRUE and 0 is FALSE. Since the `while()` function keeps going as long as the statement inside the brackets is TRUE, this will just keep it open until it is broken (here with `break()`). Following this logic, `while(0)` will actually do nothing since it evaluates to `FALSE` and therefore the loop never gets going at all!

Note that you could also just count the number of successes and make the condition `while(n < i)` which will automatically stop when you get the required `i` datasets.
