### ISSUE TITLE
Add biased subsampling to sample_phydat

### ISSUE THREAD

**Issue by julianheavyside** [julianheavyside/diversification#11]
Use bias function I wrote

**Comment by julianheavyside** [comment]
simulate over a range of sampling biases

**Comment by julianheavyside** [comment]
what do you think about the super loop now @mwpennell ? Too much going on? 
https://github.com/julianheavyside/diversification/blob/master/analysis.R#L85-L99

**Comment by mwpennell** [comment]
while there is a lot going on here, it isn't that bad at all because it is super clear and easy to read. 

the other way of doing this which may or may not be more elegant is to write a function that generates a list of parameters and just `_apply` through it. however, you basically have to write this mega loop to generate the list of parameters anyways so the actual code won't be any shorter. stylistic choice -- either is fine
